# -*- coding: utf-8 -*-
"""
Solved: 10-30-2017, 14:49

Question:
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
"""

#Solving it iteratively so it is more efficient
def sum_even_fib():
    answer = 0
    f0 = 0
    f1 = 1
    while (f0 < 4000000):
        temp = f0        
        f0 = f1
        f1 += temp
        if (f0 % 2 == 0):
            answer += f0
    return answer

print(sum_even_fib())
#461372